export type CityPage = {
  slug: string;
  /** Must match an entry in `cities` in site.ts */
  name: string;
  state: string;
  /** Well-known business districts and industrial belts we recruit across. */
  hubs: string[];
  /** Sector strengths of the local economy. */
  sectors: string[];
  intro: string;
  market: string[];
  roles: { label: string; roles: string }[];
  nearby: string[];
};

export const cityPages: CityPage[] = [
  {
    slug: "delhi-ncr",
    name: "Delhi NCR",
    state: "Delhi, Haryana & Uttar Pradesh",
    hubs: [
      "Connaught Place",
      "Nehru Place",
      "Okhla & Jasola",
      "Aerocity",
      "Gurugram",
      "Noida",
      "Faridabad",
      "Ghaziabad",
    ],
    sectors: [
      "IT & software",
      "BFSI",
      "Consulting & professional services",
      "E-commerce & D2C",
      "Manufacturing",
      "Media & advertising",
    ],
    intro:
      "Delhi NCR is our home market and the region where we started in 2010. It is also the most fragmented hiring market in India — a single company often draws talent from Delhi, Gurugram, Noida, Faridabad and Ghaziabad, and commute distance decides offer acceptance as often as compensation does.",
    market: [
      "Candidates weigh commute heavily. A Noida-based candidate will frequently decline a Gurugram role at the same CTC, so we screen on location practicality before submitting a profile.",
      "Corporate headquarters, consulting firms and global capability centres sit alongside a deep manufacturing belt in Faridabad, Bhiwadi and Ghaziabad, which means the same city needs both white-collar and plant hiring.",
      "Notice periods of 60 to 90 days are standard in the corporate segment, while manufacturing and sales roles often move in 15 to 30 days.",
    ],
    roles: [
      { label: "Technology", roles: "Backend, frontend, DevOps, QA, data engineering, product" },
      { label: "BFSI", roles: "Relationship management, credit, risk, collections, operations" },
      { label: "Sales & Marketing", roles: "Enterprise sales, inside sales, performance marketing, brand" },
      { label: "Manufacturing", roles: "Production, quality, maintenance, EHS, supply chain" },
      { label: "Shared services", roles: "F&A, HRO, procurement, customer support" },
    ],
    nearby: ["gurugram", "noida", "jaipur", "chandigarh"],
  },
  {
    slug: "gurugram",
    name: "Gurugram",
    state: "Haryana",
    hubs: [
      "Cyber City",
      "Golf Course Road",
      "Sohna Road",
      "Udyog Vihar",
      "Manesar",
      "Sector 44 & 48",
    ],
    sectors: [
      "IT & ITeS",
      "BFSI & fintech",
      "Consulting",
      "Automotive (Manesar)",
      "Start-ups & D2C",
      "Global capability centres",
    ],
    intro:
      "Gurugram concentrates more global capability centres, consulting firms and fintech headquarters per square kilometre than anywhere else in North India — and with them, the most competitive salary benchmarks in the region.",
    market: [
      "Counter-offers are common here. We test counter-offer risk during the first screening call rather than discovering it on the joining date.",
      "Cyber City and Golf Course Road draw a different candidate profile from Udyog Vihar and Manesar, and the salary bands between them are not comparable.",
      "Manesar's automotive belt needs plant, quality and supply-chain hiring that looks nothing like the corporate hiring two kilometres away.",
    ],
    roles: [
      { label: "Technology & GCC", roles: "Engineering, cloud, data, cybersecurity, SRE" },
      { label: "Fintech & BFSI", roles: "Product, risk, underwriting, partnerships, compliance" },
      { label: "Consulting & analytics", roles: "Associates, managers, data analysts, research" },
      { label: "Automotive", roles: "Production, quality, design, vendor development" },
      { label: "Sales", roles: "Enterprise sales, key accounts, channel, inside sales" },
    ],
    nearby: ["delhi-ncr", "noida", "jaipur", "chandigarh"],
  },
  {
    slug: "noida",
    name: "Noida",
    state: "Uttar Pradesh",
    hubs: [
      "Sector 62 & 63",
      "Sector 125 & 126",
      "Sector 135 & 136",
      "Film City",
      "Greater Noida",
      "Yamuna Expressway belt",
    ],
    sectors: [
      "IT & software services",
      "BPO & shared services",
      "Media & broadcast",
      "Electronics manufacturing",
      "Education & EdTech",
      "E-commerce",
    ],
    intro:
      "Noida combines large IT services campuses, one of India's biggest BPO clusters and a fast-growing electronics manufacturing base along the Yamuna Expressway — which makes it a city where volume hiring and specialist hiring run side by side.",
    market: [
      "Sector 62 and 63 draw candidates from across East Delhi and Ghaziabad, which widens the available pool considerably for mid-level roles.",
      "Shift-based BPO hiring needs a different sourcing approach from day-shift IT hiring: transport routes, shift preference and locality all decide who actually joins.",
      "Greater Noida and the Expressway belt are adding manufacturing headcount faster than the local talent supply, so relocation and bussing plans often form part of the hiring brief.",
    ],
    roles: [
      { label: "IT services", roles: "Developers, testers, support engineers, project managers" },
      { label: "BPO & shared services", roles: "Voice, chat, email support, collections, F&A" },
      { label: "Electronics manufacturing", roles: "Line operators, quality, SMT technicians, supervisors" },
      { label: "Media", roles: "Production, editing, broadcast operations, content" },
      { label: "EdTech", roles: "Academic counselling, inside sales, content, operations" },
    ],
    nearby: ["delhi-ncr", "gurugram", "lucknow", "jaipur"],
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    hubs: [
      "Bandra Kurla Complex",
      "Lower Parel",
      "Andheri & SEEPZ",
      "Powai",
      "Goregaon",
      "Navi Mumbai",
      "Thane",
    ],
    sectors: [
      "BFSI & capital markets",
      "Media & entertainment",
      "Pharmaceuticals",
      "Logistics & shipping",
      "Real estate",
      "FMCG",
    ],
    intro:
      "Mumbai is India's financial capital, and hiring here reflects it: the deepest BFSI talent pool in the country, the highest compensation benchmarks, and candidates who evaluate a commute across the city as seriously as they evaluate the role.",
    market: [
      "Location matters more in Mumbai than almost anywhere else. A candidate in Thane may decline a BKC role that a Bandra-based candidate would take at the same number.",
      "BFSI and capital markets roles often need regulatory familiarity, so we screen for the specific licence, product or regulator exposure rather than generic domain experience.",
      "Navi Mumbai and Thane have become genuine alternatives to the island city for back-office, technology and shared-services hiring, usually at a lower cost base.",
    ],
    roles: [
      { label: "BFSI", roles: "Investment banking, wealth, credit, risk, compliance, operations" },
      { label: "Media & entertainment", roles: "Production, content, digital, ad sales, post-production" },
      { label: "Pharma", roles: "Regulatory affairs, quality, formulation, medical affairs, field sales" },
      { label: "Logistics", roles: "Freight forwarding, customs, warehouse, shipping operations" },
      { label: "Technology", roles: "Engineering, data, product, cybersecurity" },
    ],
    nearby: ["pune", "ahmedabad", "bengaluru", "indore"],
  },
  {
    slug: "pune",
    name: "Pune",
    state: "Maharashtra",
    hubs: [
      "Hinjewadi",
      "Kharadi & EON",
      "Magarpatta",
      "Baner & Balewadi",
      "Chakan & Talegaon",
      "Pimpri-Chinchwad",
    ],
    sectors: [
      "IT & software",
      "Automotive & auto components",
      "Engineering & manufacturing",
      "KPO & analytics",
      "Education",
      "Global capability centres",
    ],
    intro:
      "Pune is one of the few Indian cities with genuine depth in both technology and manufacturing. Hinjewadi and Kharadi supply the IT and GCC talent, while the Chakan and Pimpri belts hold one of the country's strongest automotive and engineering pools.",
    market: [
      "Cross-city commute between Hinjewadi and Kharadi is a real constraint, and it shows up in offer acceptance — we factor it into shortlisting rather than after.",
      "The automotive belt around Chakan, Talegaon and Ranjangaon needs plant, quality and vendor-development hiring that competes with Aurangabad and Nashik for the same candidates.",
      "Pune's engineering colleges make it one of the strongest campus hiring markets in western India, especially for graduate engineer trainee intakes.",
    ],
    roles: [
      { label: "Technology & GCC", roles: "Java, .NET, embedded, cloud, data engineering, QA" },
      { label: "Automotive", roles: "Design, production, quality, testing, vendor development" },
      { label: "Engineering", roles: "Mechanical design, project engineering, maintenance, EHS" },
      { label: "KPO & analytics", roles: "Research, analytics, actuarial, F&A processing" },
      { label: "Campus intakes", roles: "Graduate engineer trainees, management trainees" },
    ],
    nearby: ["mumbai", "bengaluru", "ahmedabad", "indore"],
  },
  {
    slug: "bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    hubs: [
      "Outer Ring Road",
      "Whitefield",
      "Electronic City",
      "Koramangala & HSR Layout",
      "Hebbal & Manyata",
      "Indiranagar",
    ],
    sectors: [
      "IT & product engineering",
      "Start-ups & SaaS",
      "Global capability centres",
      "Aerospace & defence",
      "Biotechnology",
      "E-commerce",
    ],
    intro:
      "Bengaluru has the deepest technology talent pool in India and, because of that, the most competitive one. Candidates here routinely run three or four processes at once, which makes speed of feedback the single biggest factor in whether you close your first-choice candidate.",
    market: [
      "Offer-to-joining drop-out is higher in Bengaluru than anywhere else in India. Structured contact through notice period is not optional here — it is the difference between a hire and a restart.",
      "Product companies, services firms and GCCs pay very differently for the same title, so benchmarking has to be done against the specific company type, not the city average.",
      "Outer Ring Road and Whitefield candidates rarely move to Electronic City roles without a meaningful reason, so commute screening genuinely changes acceptance rates.",
    ],
    roles: [
      { label: "Product engineering", roles: "Backend, frontend, mobile, platform, SRE, security" },
      { label: "Data & AI", roles: "Data engineering, ML engineering, analytics, data science" },
      { label: "Product & design", roles: "Product management, UX research, product design" },
      { label: "GCC leadership", roles: "Engineering managers, directors, site leadership" },
      { label: "Go-to-market", roles: "Enterprise sales, customer success, solutions engineering" },
    ],
    nearby: ["hyderabad", "chennai", "pune", "coimbatore"],
  },
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    hubs: [
      "HITEC City",
      "Gachibowli",
      "Madhapur",
      "Financial District",
      "Genome Valley",
      "Kondapur",
    ],
    sectors: [
      "IT & software",
      "Global capability centres",
      "Pharmaceuticals & life sciences",
      "BPO & shared services",
      "Aerospace",
      "Data centres",
    ],
    intro:
      "Hyderabad has become the default second campus for global capability centres, and Genome Valley gives it a pharmaceutical and life-sciences pool that few other Indian cities can match. The two ecosystems barely overlap, and hiring for each needs different consultants.",
    market: [
      "GCC expansion has pushed technology compensation close to Bengaluru levels for senior roles, while mid-level bands still run slightly lower.",
      "Pharma and life-sciences hiring around Genome Valley and the Medak belt needs regulatory and GMP familiarity, which is not interchangeable with generic manufacturing experience.",
      "The city's relatively contained geography makes commute a smaller constraint than in Bengaluru or Mumbai, which widens the practical candidate pool for most roles.",
    ],
    roles: [
      { label: "Technology & GCC", roles: "Engineering, cloud, data, platform, QA, DevOps" },
      { label: "Pharma & life sciences", roles: "Formulation, analytical R&D, QA/QC, regulatory affairs" },
      { label: "BPO & shared services", roles: "Voice, non-voice, F&A, HRO, procurement" },
      { label: "Sales & marketing", roles: "Enterprise sales, inside sales, digital marketing" },
      { label: "Infrastructure", roles: "Data centre operations, facilities, network engineering" },
    ],
    nearby: ["bengaluru", "chennai", "pune", "kochi"],
  },
  {
    slug: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    hubs: [
      "OMR (Sholinganallur & Perungudi)",
      "Guindy",
      "Ambattur",
      "Sriperumbudur",
      "Oragadam",
      "Taramani",
    ],
    sectors: [
      "IT & software services",
      "Automotive & EV",
      "Electronics manufacturing",
      "BFSI back office",
      "Healthcare",
      "Logistics & ports",
    ],
    intro:
      "Chennai runs two large hiring economies in parallel: the IT corridor along OMR, and one of India's densest automotive and electronics manufacturing belts around Sriperumbudur and Oragadam. Volume manufacturing hiring here is a specialism in its own right.",
    market: [
      "The Sriperumbudur and Oragadam belt hires in cohorts rather than individually, so drives, transport planning and joining forecasts matter more than CV quality alone.",
      "Tamil language ability is a genuine requirement for most plant-floor, field sales and customer-facing roles, and we screen for it explicitly.",
      "OMR's IT corridor competes directly with Bengaluru for the same senior technology candidates, usually on cost of living and family location rather than on compensation.",
    ],
    roles: [
      { label: "IT services", roles: "Developers, testers, support, infrastructure, project management" },
      { label: "Automotive & EV", roles: "Production, quality, design, battery and powertrain engineering" },
      { label: "Electronics manufacturing", roles: "Operators, SMT, quality, industrial engineering" },
      { label: "BFSI back office", roles: "Operations, reconciliation, customer service, collections" },
      { label: "Healthcare", roles: "Clinical, hospital operations, diagnostics, medical devices" },
    ],
    nearby: ["bengaluru", "coimbatore", "hyderabad", "kochi"],
  },
  {
    slug: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    hubs: [
      "SG Highway",
      "Prahlad Nagar",
      "GIFT City (Gandhinagar)",
      "Sanand",
      "Changodar",
      "Vatva",
    ],
    sectors: [
      "Pharmaceuticals & chemicals",
      "Textiles",
      "Automotive",
      "Fintech & IFSC (GIFT City)",
      "Engineering",
      "Agri-processing",
    ],
    intro:
      "Ahmedabad's hiring market is built on manufacturing — pharma, chemicals, textiles and automotive — with a growing financial-services layer at GIFT City that is pulling BFSI and fintech talent into Gujarat for the first time at scale.",
    market: [
      "The Sanand and Changodar industrial belts need plant, quality and maintenance hiring in volume, often with relocation support from other Gujarat cities.",
      "GIFT City roles compete with Mumbai for BFSI candidates, and the pitch that works is usually cost of living and commute rather than headline CTC.",
      "Gujarati language ability is commonly required for field sales, plant supervision and customer-facing roles, and we screen for it upfront.",
    ],
    roles: [
      { label: "Pharma & chemicals", roles: "Production, QA/QC, R&D, regulatory, EHS" },
      { label: "Textiles", roles: "Production, merchandising, quality, export documentation" },
      { label: "Automotive", roles: "Line operations, quality, maintenance, vendor development" },
      { label: "BFSI & fintech", roles: "Operations, compliance, treasury, product, technology" },
      { label: "Engineering", roles: "Design, project engineering, procurement, maintenance" },
    ],
    nearby: ["mumbai", "pune", "indore", "jaipur"],
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    hubs: [
      "Salt Lake Sector V",
      "New Town & Rajarhat",
      "Park Street",
      "Dalhousie",
      "Howrah industrial belt",
    ],
    sectors: [
      "IT & ITeS",
      "BFSI back office",
      "FMCG & distribution",
      "Manufacturing & engineering",
      "Healthcare",
      "Education",
    ],
    intro:
      "Kolkata offers a large, stable talent pool at a materially lower cost base than the western and southern metros, which is why shared-services and back-office operations keep expanding here. Retention is also noticeably better than in the high-churn tech metros.",
    market: [
      "Attrition in Kolkata runs lower than in Bengaluru or Gurugram for comparable roles, which changes the economics of building a team here.",
      "Salt Lake Sector V and New Town carry most of the IT and ITeS headcount, while eastern India's distribution and FMCG hiring is run out of central Kolkata.",
      "Bengali language ability is a practical requirement for field sales, collections and customer-facing roles across eastern India.",
    ],
    roles: [
      { label: "IT & ITeS", roles: "Developers, support engineers, voice and non-voice processing" },
      { label: "BFSI back office", roles: "Operations, reconciliation, KYC, collections" },
      { label: "FMCG & distribution", roles: "Area sales, distributor management, supply chain" },
      { label: "Manufacturing", roles: "Production, maintenance, quality, plant administration" },
      { label: "Healthcare", roles: "Hospital operations, clinical, diagnostics, medical sales" },
    ],
    nearby: ["bhubaneswar", "lucknow", "delhi-ncr", "mumbai"],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    hubs: [
      "Sitapura",
      "Malviya Nagar",
      "Mahindra World City",
      "Vishwakarma Industrial Area",
      "Tonk Road",
    ],
    sectors: [
      "IT & BPO",
      "Gems & jewellery",
      "Handicraft & export",
      "Tourism & hospitality",
      "Manufacturing",
      "Education",
    ],
    intro:
      "Jaipur has become a genuine tier-2 alternative for BPO and shared-services operations, with a lower cost base than NCR and a large graduate pool. It also holds India's most specialised gems, jewellery and handicraft export talent.",
    market: [
      "Salary expectations run meaningfully below NCR for comparable roles, which is the main reason companies set up delivery centres here.",
      "The graduate pool is large but competition for experienced specialists is limited, so senior hires often involve attracting people back from NCR or Mumbai.",
      "Tourism and hospitality hiring is seasonal, and planning drives around the season rather than against it makes a large difference to fill rates.",
    ],
    roles: [
      { label: "BPO & shared services", roles: "Voice, chat, back office, collections, quality" },
      { label: "Gems & jewellery", roles: "Design, production, merchandising, export documentation" },
      { label: "Hospitality", roles: "Front office, F&B, housekeeping, operations management" },
      { label: "Manufacturing", roles: "Production, quality, maintenance, stores" },
      { label: "Sales", roles: "Field sales, channel sales, inside sales, collections" },
    ],
    nearby: ["delhi-ncr", "gurugram", "ahmedabad", "indore"],
  },
  {
    slug: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    hubs: [
      "Vijay Nagar",
      "Super Corridor",
      "Pithampur",
      "Sanwer Road",
      "Crystal IT Park",
    ],
    sectors: [
      "Manufacturing",
      "Pharmaceuticals",
      "IT & ITeS",
      "Agri & food processing",
      "Automotive components",
      "Education",
    ],
    intro:
      "Indore is central India's commercial centre, with the Pithampur industrial belt on one side and a growing IT and shared-services cluster along the Super Corridor on the other. Cost base and attrition both run well below the metros.",
    market: [
      "Pithampur hires in volume for automotive components, pharma and FMCG manufacturing, and drives work better here than individual sourcing.",
      "The Super Corridor IT cluster is still young, so mid-senior technology hiring frequently involves relocating candidates from Pune, Bengaluru or NCR back to their home state.",
      "Indore's management and engineering colleges make it a strong campus market for central India intakes.",
    ],
    roles: [
      { label: "Manufacturing", roles: "Production, quality, maintenance, industrial engineering" },
      { label: "Pharma", roles: "Production, QA/QC, packaging, regulatory documentation" },
      { label: "IT & ITeS", roles: "Developers, support engineers, back-office processing" },
      { label: "Food processing", roles: "Plant operations, food safety, quality, supply chain" },
      { label: "Sales & distribution", roles: "Area sales, distributor management, retail expansion" },
    ],
    nearby: ["ahmedabad", "pune", "jaipur", "mumbai"],
  },
  {
    slug: "chandigarh",
    name: "Chandigarh",
    state: "Chandigarh, Punjab & Haryana",
    hubs: [
      "Chandigarh IT Park",
      "Mohali",
      "Panchkula",
      "Industrial Area Phase 1 & 2",
      "Zirakpur",
    ],
    sectors: [
      "IT & software services",
      "BPO",
      "Pharmaceuticals",
      "Education",
      "Manufacturing",
      "Healthcare",
    ],
    intro:
      "The Chandigarh tricity — Chandigarh, Mohali and Panchkula — is North India's main tier-2 hiring market, with an IT and BPO base, a strong education ecosystem and pharmaceutical manufacturing in the surrounding belt.",
    market: [
      "Candidates here often prefer staying in the tricity over relocating to NCR, which makes retention better than in Gurugram for comparable roles.",
      "The education cluster produces a steady graduate supply, making Chandigarh a practical base for fresher-heavy delivery centres.",
      "Punjabi and Hindi language ability is standard for field-facing roles across Punjab, Haryana and Himachal.",
    ],
    roles: [
      { label: "IT services", roles: "Developers, QA, support engineers, project coordination" },
      { label: "BPO", roles: "Voice, chat, email support, back office, quality" },
      { label: "Pharma", roles: "Production, QA/QC, packaging, field sales" },
      { label: "Education", roles: "Academic, admissions, counselling, administration" },
      { label: "Healthcare", roles: "Hospital operations, clinical, diagnostics" },
    ],
    nearby: ["delhi-ncr", "gurugram", "lucknow", "jaipur"],
  },
  {
    slug: "coimbatore",
    name: "Coimbatore",
    state: "Tamil Nadu",
    hubs: [
      "Peelamedu",
      "Tidel Park Coimbatore",
      "SIDCO Industrial Estate",
      "Saravanampatti",
      "Kurichi",
    ],
    sectors: [
      "Textiles & garments",
      "Pumps, motors & engineering",
      "Automotive components",
      "IT & software",
      "Education",
      "Healthcare",
    ],
    intro:
      "Coimbatore is one of India's strongest engineering manufacturing clusters — pumps, motors, castings and auto components — with a growing IT presence around Saravanampatti and Tidel Park. Engineering talent here is deep and unusually stable.",
    market: [
      "Manufacturing attrition is low and tenure is long, so hiring here is less about speed and more about finding candidates genuinely open to a move.",
      "The engineering college cluster in and around Coimbatore makes it a reliable campus market for technical fresher intakes.",
      "Tamil language ability is required for most plant, supervisory and customer-facing roles.",
    ],
    roles: [
      { label: "Engineering & manufacturing", roles: "Design, production, quality, maintenance, foundry" },
      { label: "Textiles", roles: "Spinning, knitting, merchandising, quality, export" },
      { label: "Automotive components", roles: "Machining, assembly, quality, vendor development" },
      { label: "IT", roles: "Developers, QA, support, product engineering" },
      { label: "Campus intakes", roles: "Graduate engineer trainees, diploma technicians" },
    ],
    nearby: ["chennai", "bengaluru", "kochi", "hyderabad"],
  },
  {
    slug: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    hubs: [
      "Gomti Nagar",
      "Vibhuti Khand",
      "Hazratganj",
      "Amausi Industrial Area",
      "Sushant Golf City",
    ],
    sectors: [
      "BFSI & insurance",
      "Healthcare",
      "Education",
      "IT & BPO",
      "FMCG distribution",
      "Government & PSU ecosystem",
    ],
    intro:
      "Lucknow is the commercial and administrative centre of Uttar Pradesh, and the natural base for any company building a distribution, sales or service network across the state. BFSI, insurance and healthcare account for most white-collar hiring here.",
    market: [
      "Lucknow works best as a regional hub — a team here typically covers Kanpur, Varanasi, Gorakhpur, Prayagraj and the wider UP market.",
      "Field sales, collections and insurance hiring dominate volume requirements, and local language ability is essential for all of them.",
      "Senior specialist hiring usually involves attracting candidates back from NCR, which works when family location is part of the pitch.",
    ],
    roles: [
      { label: "BFSI & insurance", roles: "Branch banking, agency, collections, credit, operations" },
      { label: "Healthcare", roles: "Hospital operations, clinical, diagnostics, medical sales" },
      { label: "Education", roles: "Academic, admissions, counselling, administration" },
      { label: "FMCG & distribution", roles: "Area sales, distributor management, rural sales" },
      { label: "IT & BPO", roles: "Support engineers, voice and non-voice processing" },
    ],
    nearby: ["delhi-ncr", "noida", "kolkata", "indore"],
  },
  {
    slug: "kochi",
    name: "Kochi",
    state: "Kerala",
    hubs: [
      "Infopark Kakkanad",
      "SmartCity Kochi",
      "Willingdon Island",
      "Kalamassery",
      "Ernakulam",
    ],
    sectors: [
      "IT & software",
      "Logistics & ports",
      "Tourism & hospitality",
      "Marine & shipping",
      "Healthcare",
      "Spices & food export",
    ],
    intro:
      "Kochi combines an established IT cluster at Infopark and SmartCity with India's south-western port and logistics gateway. It also has one of the country's most internationally mobile talent pools, which shapes both supply and expectations.",
    market: [
      "A significant share of experienced candidates weigh Gulf opportunities alongside domestic ones, so offers are benchmarked against more than the Indian market.",
      "Logistics, shipping and marine roles around Willingdon Island and Vallarpadam need port-specific experience that is not interchangeable with general supply chain.",
      "Malayalam language ability is required for most customer-facing, field and healthcare roles across Kerala.",
    ],
    roles: [
      { label: "IT", roles: "Developers, QA, product engineering, support, data" },
      { label: "Logistics & shipping", roles: "Freight forwarding, customs, port operations, documentation" },
      { label: "Tourism & hospitality", roles: "Front office, F&B, operations, travel sales" },
      { label: "Healthcare", roles: "Clinical, hospital operations, diagnostics, medical devices" },
      { label: "Export & trading", roles: "Procurement, quality, export documentation, compliance" },
    ],
    nearby: ["coimbatore", "chennai", "bengaluru", "hyderabad"],
  },
  {
    slug: "bhubaneswar",
    name: "Bhubaneswar",
    state: "Odisha",
    hubs: [
      "Info City",
      "Chandaka Industrial Estate",
      "Patia",
      "Khordha belt",
      "Cuttack corridor",
    ],
    sectors: [
      "IT & ITeS",
      "Metals & mining services",
      "Education",
      "Healthcare",
      "Manufacturing",
      "Government & PSU ecosystem",
    ],
    intro:
      "Bhubaneswar is eastern India's fastest-growing tier-2 market, anchored by an IT cluster at Info City, a large student population and the metals and mining economy of the wider Odisha belt.",
    market: [
      "The university cluster makes Bhubaneswar a strong fresher and campus market, particularly for IT and engineering intakes.",
      "Metals, mining and heavy-engineering hiring across Odisha is usually run out of Bhubaneswar even when the site is in Angul, Jajpur or Rourkela.",
      "Cost base and attrition both run below Kolkata, which is why shared-services operations are increasingly choosing it over larger eastern metros.",
    ],
    roles: [
      { label: "IT & ITeS", roles: "Developers, support engineers, back-office processing" },
      { label: "Metals & mining", roles: "Plant operations, maintenance, safety, logistics" },
      { label: "Education", roles: "Academic, admissions, counselling, administration" },
      { label: "Healthcare", roles: "Hospital operations, clinical, diagnostics" },
      { label: "Campus intakes", roles: "Graduate engineer trainees, management trainees" },
    ],
    nearby: ["kolkata", "hyderabad", "chennai", "lucknow"],
  },
];

export const cityBySlug = new Map(cityPages.map((city) => [city.slug, city]));
